version: '3.3'
services:
  frontend.reg:
    image: joxit/docker-registry-ui:2
    container_name: frontend.reg
    depends_on:
      - pozos-registry
    ports: 
      - "8080:80"
    environment:
      - NGINX_PROXY_PASS_URL=http://pozos-registry:5000
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Pozos
      - SINGLE_REGISTRY=true
    networks:
      - student_list.network

networks:
  student_list.network: